### ISSUE TITLE
User data is not stored when logging in using facebook oath.

### ISSUE THREAD

**Issue by Poujhit** [Chennai-Sharks/Fantasy-11#1]
**Describe the bug**
When users click on the Facebook login button, their data is not being stored anywhere in the database.  Only the JWT token are being generated and their access is given. 

**Possible Solution**

- When a user logs in using Facebook, check whether the user is already present or not.
- If the user is already present, just set the JWT access cookie for that user.
- Otherwise, create a new user with their email-id and set the JWT access cookie for that user.

**Comment by NikhileshJr08** [comment]
The issue has been successfully solved
